### ISSUE TITLE
Remember last select row ;)

### ISSUE THREAD

**Issue by paoloandrea** [chenzeyu/CZPicker#10]
Hello,
thanks for your excellent work.
I wanted to know if there is a way to recall the previous active selection.
Eg. By calling the "selectRow"
Thank You.

**Comment by chenzeyu** [comment]
Currently there's no method to recall the last selected item. I wonder in what scenario would you need such option and what is your proposed solution?

I am not very clear about this, should it be a button on the picker so that the user can undo the selection or it is a method in source code that the developer can do something with it?

**Comment by zobnec** [comment]
I think it is very useful if it can recall the previous active selection.
For example:
I select the banana in the picker view,and sometimes i want to know what i select last time;So if there is a  recall method,when i click the button,and the picker view will show again with the selected item;

**Comment by chenzeyu** [comment]
@zobnec sounds reasonable.

Keeping a stack of previously selected items or just keep the latest selected item, the first solution allows the picker to recall all items in multiple selection mode.

Would you be interested in working on that and give me a patch?

**Comment by chenzeyu** [comment]
#15
