### ISSUE TITLE
I cannot get the delegate methods to work on Swift

### ISSUE THREAD

**Issue by moyoteg** [chenzeyu/CZPicker#5]

**Comment by chenzeyu** [comment]
It is supposed to work on Swift with cocoapods' ```use_frameworks!``` on.
However I have the same problem making the delegate & dataSource working.
I'm currently digging into this issue and aim to resolve it asap.

**Comment by moyoteg** [comment]
Found the solution! you just have to change the name of the delegate methods, for example instead of naming the method
 optional func CZPickerView(pickerView: CZPickerView!, didConfirmWithItemAtRow row: Int)

change it to:  
   optional func czPickerView(pickerView: CZPickerView!, didConfirmWithItemAtRow row: Int)

http://stackoverflow.com/questions/30033523/what-is-wrong-that-shows-use-of-undeclared-type-after-adding-an-function

**Comment by chenzeyu** [comment]
Hey moyoteg, that's great, thanks for what you have found.

Actually the original names did not conform to Apple's naming conventions, though it works fine in obj-c. I've changed all protocol methods' names to start with lowercases and now it works in swift!

Fixed in 0.3.5 a733555a70641c66f1ad6bbf713ff087daff3b56

**Comment by moyoteg** [comment]
Thank you!
